routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
  
Route::get('/home', 'CursoController@index')->name('home');
Route::get("/listadocursos", "CursoController@listadocursos")->name('listadocursos');
Route::get("/listadocursos/{curso}/suscribir", "CursoController@suscribir")->name('suscribir');
Route::post('/listadocursos/suscribir', 'CursoController@guardar')->name('guardar');
Route::post('/contacto/guardar', [CursoController::class,'guardar'])->name('guardar');

Route::group(['middleware' => 'auth'], function () {  
    Route::resource('cursos', CursoController::class);
});   



app/Curso.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Curso extends Model
{
    protected $fillable = [
        'nombre','duracion','fechainicio','fechafin','sede','jornada','descripcion','imagen'
    ];
}

app/Http/Controllers/CursoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use App\Curso;
use App\Subscriptions;
use App\Mail\CorreoEnviado;

class CursoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cursos = Curso::latest()->paginate(5);
    
        return view('cursos.index',compact('cursos'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cursos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre'        => 'required',
            'duracion'      => 'required',
            'fechainicio'   => 'required',
            'fechafin'      => 'required',
            'sede'          => 'required',
            'jornada'       => 'required',
            'descripcion'    => 'required',
            'imagen'        => 'required',
        ]);
    
        //Curso::create($request->all());

        $curso =new Curso;
        $curso->nombre        = $request->nombre;
        $curso->duracion      = $request->duracion;
        $curso->fechainicio   = $request->fechainicio;
        $curso->fechafin      = $request->fechafin;
        $curso->sede          = $request->sede;
        $curso->jornada       = $request->jornada;
        $curso->descripcion   = $request->descripcion;

        if ($request->hasFile('imagen')){
            $file           = $request->file("imagen");
            $nombrearchivo  = $file->getClientOriginalName();
            $file->move(public_path("storage/"),$nombrearchivo);
            $curso->imagen        = $nombrearchivo;
        }

        $curso->save();

     
        return redirect()->route('cursos.index')
                        ->with('success','Curso credo correctamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

     /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Curso  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Curso $curso)
    {
        return view('cursos.edit',compact('curso'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Curso  $curso
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Curso $curso)
    {
        $request->validate([
            'nombre'        => 'required',
            'duracion'      => 'required',
            'fechainicio'   => 'required',
            'fechafin'      => 'required',
            'sede'          => 'required',
            'jornada'       => 'required',
            'descripcion'    => 'required',
            'imagen'        => 'required',
        ]);

        if ($request->hasFile('imagen')){
            $file           = $request->file("imagen");
            $nombrearchivo  = $file->getClientOriginalName();
            $file->move(public_path("storage/"),$nombrearchivo);
        }
    
        $curso->update($request->all());

        $curso->where('id',$curso->id)
                ->update(['imagen'=> $nombrearchivo]);
    
        return redirect()->route('cursos.index')
                        ->with('success','Curso actualizado correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Curso  $curso
     * @return \Illuminate\Http\Response
     */
    public function destroy(Curso $curso)
    {
        $curso->delete();
    
        return redirect()->route('cursos.index')
                        ->with('success','Curso eliminado correctamente');
    }

    public function listadocursos()
    {
        $cursos = Curso::latest()->paginate(5);
    
        return view('listadocursos',compact('cursos'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function suscribir(Curso $curso)
    {
        return view('suscribir',compact('curso'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function guardar(Request $request)
    {
        $request->validate([
            'curso'          => 'required',
            'nombre'         => 'required',
            'email'          => 'required',
            'tipo'           => 'required',
            'identificacion' => 'required',
            'optradio'       => 'required',
            'pago'           => 'required',
        ]);

        $correo = $request->email;
        $cursoinscrito = $request->curso;
        $informacion = Curso::where("nombre","=",$request->curso)->get()->toArray();
    
        $suscribir =new Subscriptions;
        $suscribir->curso           = $request->curso;
        $suscribir->nombre          = $request->nombre;
        $suscribir->email           = $request->email;
        $suscribir->tipo            = $request->tipo;
        $suscribir->identificacion  = $request->identificacion;
        $suscribir->optradio        = $request->optradio;
        $suscribir->pago            = $request->pago;

        $suscribir->save();

        
        Mail::to($correo)->send(new CorreoEnviado($cursoinscrito,$informacion));

     
        return redirect()->route('listadocursos')
                        ->with('success','Se registro correctamente en el curso');
    }

    
}

resources/views/cursos/create.blade.php
@extends('layouts.app')
  
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">CREAR NUEVO CURSO</div>
                    <div class="card-body">                        
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <strong>¡Ups!</strong> Hubo algunos problemas con tu entrada..<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        
                        <form enctype="multipart/form-data" action="{{ route('cursos.store') }}" method="POST">
                            @csrf
                        
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Nombre:</strong>
                                        <input type="text" name="nombre" class="form-control" placeholder="Nombre">
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Fecha inicio:</strong>
                                        <input type="date" name="fecha-inicio" class="form-control">
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Fecha fin:</strong>
                                        <input type="date" name="fecha-fin" class="form-control">
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Duracion:</strong>
                                        <input type="text" name="duracion" class="form-control" placeholder="Duracion del curso">
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Sede:</strong>
                                        <select name="sede" class="form-control">
                                            <option></option>
                                            <option value="Sede Principal" > Sede Principal</option>
                                            <option value="Sede Sur" > Sede Sur</option>
                                            <option value="Sede Norte" > Sede Norte</option>
                                            
                                        </select> 
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Jornada:</strong>
                                        <select name="jornada" class="form-control">
                                            <option></option>
                                            <option value="Diurno"> Diurno</option>
                                            <option value="Nocturno"> Nocturno</option>
                                            <option value="Sabatino"> Sabatino</option>                                          
                                        </select> 
                                    </div>
                                </div>
                                                            
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Imagen:</strong>
                                        <input type="file" name="imagen">
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Descripcion:</strong>
                                        <textarea class="form-control" name="descripcion" id="descripcion" rows="3" placeholder="Descripcion...."></textarea>
                                    </div>
                                </div>   
                                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                        <button type="submit" class="btn btn-primary">Guardar curso</button>
                                        <a class="btn btn-primary" href="{{ route('cursos.index') }}"> Volver</a>
                                </div>
                            </div>
                        
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


resources/views/cursos/edit.blade.php
@extends('layouts.app')
   
@section('content')
    <div class="container"> 
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">EDITAR LOS CURSOS</div>
                    <div class="card-body">                     
                        @if ($errors->any())
                            <div class="alert alert-danger">
                              <strong>¡Ups!</strong> Hubo algunos problemas con tu entrada..<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                    
                        <form enctype="multipart/form-data" action="{{ route('cursos.update',$curso->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                    
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Nombre:</strong>
                                        <input type="text" name="nombre" value="{{ $curso->nombre }}" class="form-control" placeholder="Nombre">
                                    </div>
                                </div>

                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Fecha inicio:</strong>
                                        <input type="date" name="fechainicio" value="{{ $curso->fechainicio }}" class="form-control">
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Fecha fin:</strong>
                                        <input type="date" name="fechafin" value="{{ $curso->fechafin }}" class="form-control">
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Duracion:</strong>
                                        <input type="text" name="duracion" value="{{ $curso->duracion }}" class="form-control" placeholder="Duracion">
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Sede:</strong>
                                        <select name="sede" class="form-control">
                                            <option></option>
                                            
                                            <option value="Sede Principal" @if ($curso->sede == "Sede Principal") selected @endif > Sede Principal</option>
                                            <option value="Sede Sur" @if ($curso->sede == "Sede Sur") selected @endif > Sede Sur</option>
                                            <option value="Sede Norte" @if ($curso->sede == "Sede Norte") selected @endif > Sede Norte</option>
                                            
                                        </select> 
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Jornada:</strong>
                                        <select name="jornada" class="form-control">
                                            <option></option>
                                            <option value="Diurno" @if ($curso->jornada == "Diurno") selected @endif > Diurno</option>
                                            <option value="Nocturno" @if ($curso->jornada == "Nocturno") selected @endif > Nocturno</option>
                                            <option value="Sabatino" @if ($curso->jornada == "Sabatino") selected @endif > Sabatino</option>                                          
                                        </select> 
                                    </div>
                                </div>
                               
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Imagen:</strong>
                                        <input type="text" value="{{ $curso->imagen }}" class="form-control" readonly><br>
                                        <input type="file" name="imagen">
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Descripcion:</strong>
                                        <input type="text" name="descripcion" value="{{ $curso->descripcion }}" class="form-control" placeholder="Descripcion">
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Actualizar</button>
                                <a class="btn btn-primary" href="{{ route('cursos.index') }}"> Volver</a>
                                </div>
                            </div>
                    
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cursos/index.blade.php
@extends('layouts.app')
 
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">LISTO DE CURSOS</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-12 margin-tb">
                                <div class="pull-right">
                                    <a class="btn btn-success" href="{{ route('cursos.create') }}"> Crear nuevo curso</a>
                                </div>
                            </div>
                        </div>

                        <br>
                    
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif

                        <div class="form-group">
                            <input type="text" class="form-control pull-right" style="width:20%" id="search" placeholder=" Buscar...">
                        </div>

                        <div style="overflow-x:auto;">
                        <table id="mytable" class="table">
                            <tr>
                                <th>No</th>
                                <th>Nombre</th>
                                <th>Duracion</th>
                                <th nowrap>Fecha Inicio</th>
                                <th nowrap>Fecha Fin</th>
                                <th nowrap>Sede</th>
                                <th>Jornada</th>
                                <th>Descripcion</th>
                                <th>Imagen</th>
                                <th colspan='2'>Herramientas</th>
                            </tr>
                            @foreach ($cursos as $curso)
                            <tr>
                                <td>{{ $curso->id }}</td>
                                <td>{{ $curso->nombre }}</td>
                                <td>{{ $curso->duracion }}</td>
                                <td nowrap>{{ $curso->fechainicio }}</td>
                                <td nowrap>{{ $curso->fechafin }}</td>
                                <td nowrap>{{ $curso->sede }}</td>
                                <td>{{ $curso->jornada }}</td>
                                <td>{{ $curso->descripcion }}</td>
                                <td>
                                    <img class="img-rounded" width="70" height="90" src="storage/{{ $curso->imagen }}" alt="image">
                                <td>    
                                    <a class="btn btn-primary" href="{{ route('cursos.edit',$curso->id) }}">Actualizar</a>  
                                </td> 
                                <td> 
                                    <form action="{{ route('cursos.destroy',$curso->id) }}" method="POST">                        
                                        @csrf
                                        @method('DELETE')
                        
                                        <button type="submit" class="btn btn-danger" onclick="confirm('QUieres eliminar el curso');">Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                        </div>
                        {!! $cursos->links() !!}
                    </div>
                </div>
            </div>
        </div>  
    </div>      
@endsection